#!/usr/bin/env python3
import os
from urllib.parse import urlparse
import subprocess
import tempfile
import datetime
import sys
import argparse
from SoapClient import SoapClient
import importlib.util

"""

soapsh ott gda-1.lab1.anevia.com -s benchmark/create_generic_channels.py

"""

# Initialize an ASOAP object
sys.path.append(os.path.dirname(os.path.realpath(__file__)))

MODULE_PATH = "/home/gdaguet/bin/soap-common-2.7.8/SoapClient.py"
MODULE_NAME = "SoapClient"

spec = importlib.util.spec_from_file_location(MODULE_NAME, MODULE_PATH)
modulevar = importlib.util.module_from_spec(spec)
spec.loader.exec_module(modulevar)


parser = argparse.ArgumentParser()

parser.add_argument("host")
parser.add_argument("-c", "--clean", action="store_true", required=False)

args = parser.parse_args()
print(args)

print("Configure host", args.host)

host = args.host  # "gda-1.lab1.anevia.com"
port = "8080"
user = "admin"
pwd = "paris"
service_type = "ott"
cl = SoapClient(f"{host}:{port}", service_type, (user, pwd))


# from soap import ASOAP, UTC
class UTC(datetime.tzinfo):
    def utcoffset(self, dt):
        return datetime.timedelta(0)

    def tzname(self, dt):
        return "UTC"

    def dst(self, dt):
        return datetime.timedelta(0)


# OTT Parameters
NB_CHANNEL = 3
DURATION_OFFSET = 600  # 30000
NPVR_DURATION = 1800
LIVE_WIN_LGTH = 600
SAF = "saf"
SCRAMBLING = True
CHANNEL_NAME_PREFIXE = "generic_channel_"
NPVR_NAME = "npvr"
VOD_NAME = "vod"

os.environ["CLEAR_CONF"] = "1"
os.environ["CREATE_CPIX_SERVER"] = "1"
os.environ["CREATE_SA_SAF"] = "1"
os.environ["CREATE_CHANNEL"] = "1"
os.environ["CREATE_NPVR_ASSETS"] = "0"
os.environ["CREATE_VOD_ASSETS"] = "0"

_type = "ts-generic"  # "ts-ebp"

interface = "lan1.42"
disk = "disk1"
server_url = urlparse(cl.client.options.location).netloc
server_url_without_port = server_url.split(":")[0]
localDatabase = cl.Get_ott_conf()["localDatabase"]
# cl.Set_ott_conf({"chunkDurations": ["2", "4", "6", "8" "10"]})
ip = "239.10.0.1"

sources_ip = [
    "udp://%s:20000:%s" % (ip, interface),
    "udp://%s:20001:%s" % (ip, interface),
    "udp://%s:20002:%s" % (ip, interface),
    "udp://%s:20003:%s" % (ip, interface),
    "udp://%s:20004:%s" % (ip, interface),
    "udp://%s:20005:%s" % (ip, interface),
    # "udp://%s:20010:%s" % (ip, interface),
    # "udp://%s:20011:%s" % (ip, interface),
    # "udp://%s:20012:%s" % (ip, interface),
]

cpix_file = """<?xml version="1.0" encoding="UTF-8"?>
<CPIX xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:dashif:org:cpix">
  <ContentKeyList>
    <ContentKey kid="04efba97-7fb9-4401-ad0d-1fd656aa3a17">
      <Data>
        <Secret xmlns="urn:ietf:params:xml:ns:keyprov:pskc">
          <PlainValue>ClKRphdjmB+BLRvLUhkk0Q==</PlainValue>
        </Secret>
      </Data>
    </ContentKey>
    <ContentKey kid="24642c32-4bb1-45b7-990b-8dce4d3c0c02">
      <Data>
        <Secret xmlns="urn:ietf:params:xml:ns:keyprov:pskc">
          <PlainValue>P2luEjc91pw2xFjuIVC4PA==</PlainValue>
        </Secret>
      </Data>
    </ContentKey>
    <ContentKey kid="7ac05713-d010-45d3-8a41-2f90493348bf">
      <Data>
        <Secret xmlns="urn:ietf:params:xml:ns:keyprov:pskc">
          <PlainValue>H+MSufBeP2YsQMIGa601IA==</PlainValue>
        </Secret>
      </Data>
    </ContentKey>
    <ContentKey kid="6ee8f9a8-0eea-433b-86ee-d343dccfc926">
      <Data>
        <Secret xmlns="urn:ietf:params:xml:ns:keyprov:pskc">
          <PlainValue>N+XOedTG6IkN2NpqTSmFsA==</PlainValue>
        </Secret>
      </Data>
    </ContentKey>
  </ContentKeyList>
  <DRMSystemList>
    <DRMSystem systemId="9a04f079-9840-4286-ab92-e65be0885f95" kid="04efba97-7fb9-4401-ad0d-1fd656aa3a17">
      <PSSH>AAAD6HBzc2gAAAAAmgTweZhAQoarkuZb4IhflQAAA8jIAwAAAQABAL4DPABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBFAFkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APABBAEwARwBJAEQAPgBBAEUAUwBDAFQAUgA8AC8AQQBMAEcASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBJAEQAPgBsADcAcgB2AEIATABsAC8AQQBVAFMAdABEAFIALwBXAFYAcQBvADYARgB3AD0APQA8AC8ASwBJAEQAPgA8AEwAQQBfAFUAUgBMAD4AaAB0AHQAcAA6AC8ALwBkAHIAbQAuAGMAYQBuAGEAbAAtAHAAbAB1AHMALgBjAG8AbQAvADwALwBMAEEAXwBVAFIATAA+ADwATABVAEkAXwBVAFIATAA+AGgAdAB0AHAAOgAvAC8AZAByAG0ALgBjAGEAbgBhAGwALQBwAGwAdQBzAC4AYwBvAG0ALwA8AC8ATABVAEkAXwBVAFIATAA+ADwARABTAF8ASQBEAD4AeQBZAEkAUABEAEIAYwBhADEAawBtAE0AZgBMADYAMABJAHMAZgBnAEEAUQA9AD0APAAvAEQAUwBfAEkARAA+ADwAQwBVAFMAVABPAE0AQQBUAFQAUgBJAEIAVQBUAEUAUwAgAHgAbQBsAG4AcwA9ACIAIgA+ADwAZQBuAGMAcgB5AHAAdABpAG8AbgByAGUAZgA+ADQANQAwAF8ANAAwADIANABfADIAOQAwADQAMgAwADIAMAAxADQAMwAzADwALwBlAG4AYwByAHkAcAB0AGkAbwBuAHIAZQBmAD4APAAvAEMAVQBTAFQATwBNAEEAVABUAFIASQBCAFUAVABFAFMAPgA8AEMASABFAEMASwBTAFUATQA+ADUAKwBFADcAaQA4ADkAUgBKAEwAZwA9ADwALwBDAEgARQBDAEsAUwBVAE0APgA8AC8ARABBAFQAQQA+ADwALwBXAFIATQBIAEUAQQBEAEUAUgA+AA==</PSSH>
      <ContentProtectionData>PGNlbmM6cHNzaD5BQUFENkhCemMyZ0FBQUFBbWdUd2VaaEFRb2Fya3VaYjRJaGZsUUFBQThqSUF3QUFBUUFCQUw0RFBBQlhBRklBVFFCSUFFVUFRUUJFQUVVQVVnQWdBSGdBYlFCc0FHNEFjd0E5QUNJQWFBQjBBSFFBY0FBNkFDOEFMd0J6QUdNQWFBQmxBRzBBWVFCekFDNEFiUUJwQUdNQWNnQnZBSE1BYndCbUFIUUFMZ0JqQUc4QWJRQXZBRVFBVWdCTkFDOEFNZ0F3QURBQU53QXZBREFBTXdBdkFGQUFiQUJoQUhrQVVnQmxBR0VBWkFCNUFFZ0FaUUJoQUdRQVpRQnlBQ0lBSUFCMkFHVUFjZ0J6QUdrQWJ3QnVBRDBBSWdBMEFDNEFNQUF1QURBQUxnQXdBQ0lBUGdBOEFFUUFRUUJVQUVFQVBnQThBRkFBVWdCUEFGUUFSUUJEQUZRQVNRQk9BRVlBVHdBK0FEd0FTd0JGQUZrQVRBQkZBRTRBUGdBeEFEWUFQQUF2QUVzQVJRQlpBRXdBUlFCT0FENEFQQUJCQUV3QVJ3QkpBRVFBUGdCQkFFVUFVd0JEQUZRQVVnQThBQzhBUVFCTUFFY0FTUUJFQUQ0QVBBQXZBRkFBVWdCUEFGUUFSUUJEQUZRQVNRQk9BRVlBVHdBK0FEd0FTd0JKQUVRQVBnQnNBRGNBY2dCMkFFSUFUQUJzQUM4QVFRQlZBRk1BZEFCRUFGSUFMd0JYQUZZQWNRQnZBRFlBUmdCM0FEMEFQUUE4QUM4QVN3QkpBRVFBUGdBOEFFd0FRUUJmQUZVQVVnQk1BRDRBYUFCMEFIUUFjQUE2QUM4QUx3QmtBSElBYlFBdUFHTUFZUUJ1QUdFQWJBQXRBSEFBYkFCMUFITUFMZ0JqQUc4QWJRQXZBRHdBTHdCTUFFRUFYd0JWQUZJQVRBQStBRHdBVEFCVkFFa0FYd0JWQUZJQVRBQStBR2dBZEFCMEFIQUFPZ0F2QUM4QVpBQnlBRzBBTGdCakFHRUFiZ0JoQUd3QUxRQndBR3dBZFFCekFDNEFZd0J2QUcwQUx3QThBQzhBVEFCVkFFa0FYd0JWQUZJQVRBQStBRHdBUkFCVEFGOEFTUUJFQUQ0QWVRQlpBRWtBVUFCRUFFSUFZd0JoQURFQWF3QnRBRTBBWmdCTUFEWUFNQUJKQUhNQVpnQm5BRUVBVVFBOUFEMEFQQUF2QUVRQVV3QmZBRWtBUkFBK0FEd0FRd0JWQUZNQVZBQlBBRTBBUVFCVUFGUUFVZ0JKQUVJQVZRQlVBRVVBVXdBZ0FIZ0FiUUJzQUc0QWN3QTlBQ0lBSWdBK0FEd0FaUUJ1QUdNQWNnQjVBSEFBZEFCcEFHOEFiZ0J5QUdVQVpnQStBRFFBTlFBd0FGOEFOQUF3QURJQU5BQmZBRElBT1FBd0FEUUFNZ0F3QURJQU1BQXhBRFFBTXdBekFEd0FMd0JsQUc0QVl3QnlBSGtBY0FCMEFHa0Fid0J1QUhJQVpRQm1BRDRBUEFBdkFFTUFWUUJUQUZRQVR3Qk5BRUVBVkFCVUFGSUFTUUJDQUZVQVZBQkZBRk1BUGdBOEFFTUFTQUJGQUVNQVN3QlRBRlVBVFFBK0FEVUFLd0JGQURjQWFRQTRBRGtBVWdCS0FFd0Fad0E5QUR3QUx3QkRBRWdBUlFCREFFc0FVd0JWQUUwQVBnQThBQzhBUkFCQkFGUUFRUUErQUR3QUx3QlhBRklBVFFCSUFFVUFRUUJFQUVVQVVnQStBQT09PC9jZW5jOnBzc2g+PG1zcHI6cHJvPnlBTUFBQUVBQVFDK0F6d0FWd0JTQUUwQVNBQkZBRUVBUkFCRkFGSUFJQUI0QUcwQWJBQnVBSE1BUFFBaUFHZ0FkQUIwQUhBQU9nQXZBQzhBY3dCakFHZ0FaUUJ0QUdFQWN3QXVBRzBBYVFCakFISUFid0J6QUc4QVpnQjBBQzRBWXdCdkFHMEFMd0JFQUZJQVRRQXZBRElBTUFBd0FEY0FMd0F3QURNQUx3QlFBR3dBWVFCNUFGSUFaUUJoQUdRQWVRQklBR1VBWVFCa0FHVUFjZ0FpQUNBQWRnQmxBSElBY3dCcEFHOEFiZ0E5QUNJQU5BQXVBREFBTGdBd0FDNEFNQUFpQUQ0QVBBQkVBRUVBVkFCQkFENEFQQUJRQUZJQVR3QlVBRVVBUXdCVUFFa0FUZ0JHQUU4QVBnQThBRXNBUlFCWkFFd0FSUUJPQUQ0QU1RQTJBRHdBTHdCTEFFVUFXUUJNQUVVQVRnQStBRHdBUVFCTUFFY0FTUUJFQUQ0QVFRQkZBRk1BUXdCVUFGSUFQQUF2QUVFQVRBQkhBRWtBUkFBK0FEd0FMd0JRQUZJQVR3QlVBRVVBUXdCVUFFa0FUZ0JHQUU4QVBnQThBRXNBU1FCRUFENEFiQUEzQUhJQWRnQkNBRXdBYkFBdkFFRUFWUUJUQUhRQVJBQlNBQzhBVndCV0FIRUFid0EyQUVZQWR3QTlBRDBBUEFBdkFFc0FTUUJFQUQ0QVBBQk1BRUVBWHdCVkFGSUFUQUErQUdnQWRBQjBBSEFBT2dBdkFDOEFaQUJ5QUcwQUxnQmpBR0VBYmdCaEFHd0FMUUJ3QUd3QWRRQnpBQzRBWXdCdkFHMEFMd0E4QUM4QVRBQkJBRjhBVlFCU0FFd0FQZ0E4QUV3QVZRQkpBRjhBVlFCU0FFd0FQZ0JvQUhRQWRBQndBRG9BTHdBdkFHUUFjZ0J0QUM0QVl3QmhBRzRBWVFCc0FDMEFjQUJzQUhVQWN3QXVBR01BYndCdEFDOEFQQUF2QUV3QVZRQkpBRjhBVlFCU0FFd0FQZ0E4QUVRQVV3QmZBRWtBUkFBK0FIa0FXUUJKQUZBQVJBQkNBR01BWVFBeEFHc0FiUUJOQUdZQVRBQTJBREFBU1FCekFHWUFad0JCQUZFQVBRQTlBRHdBTHdCRUFGTUFYd0JKQUVRQVBnQThBRU1BVlFCVEFGUUFUd0JOQUVFQVZBQlVBRklBU1FCQ0FGVUFWQUJGQUZNQUlBQjRBRzBBYkFCdUFITUFQUUFpQUNJQVBnQThBR1VBYmdCakFISUFlUUJ3QUhRQWFRQnZBRzRBY2dCbEFHWUFQZ0EwQURVQU1BQmZBRFFBTUFBeUFEUUFYd0F5QURrQU1BQTBBRElBTUFBeUFEQUFNUUEwQURNQU13QThBQzhBWlFCdUFHTUFjZ0I1QUhBQWRBQnBBRzhBYmdCeUFHVUFaZ0ErQUR3QUx3QkRBRlVBVXdCVUFFOEFUUUJCQUZRQVZBQlNBRWtBUWdCVkFGUUFSUUJUQUQ0QVBBQkRBRWdBUlFCREFFc0FVd0JWQUUwQVBnQTFBQ3NBUlFBM0FHa0FPQUE1QUZJQVNnQk1BR2NBUFFBOEFDOEFRd0JJQUVVQVF3QkxBRk1BVlFCTkFENEFQQUF2QUVRQVFRQlVBRUVBUGdBOEFDOEFWd0JTQUUwQVNBQkZBRUVBUkFCRkFGSUFQZ0E9PC9tc3ByOnBybz4=</ContentProtectionData>
    </DRMSystem>
    <DRMSystem systemId="9a04f079-9840-4286-ab92-e65be0885f95" kid="24642c32-4bb1-45b7-990b-8dce4d3c0c02">
      <PSSH>AAAD6HBzc2gAAAAAmgTweZhAQoarkuZb4IhflQAAA8jIAwAAAQABAL4DPABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBFAFkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APABBAEwARwBJAEQAPgBBAEUAUwBDAFQAUgA8AC8AQQBMAEcASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBJAEQAPgBNAGkAeABrAEoATABGAEwAdAAwAFcAWgBDADQAMwBPAFQAVAB3AE0AQQBnAD0APQA8AC8ASwBJAEQAPgA8AEwAQQBfAFUAUgBMAD4AaAB0AHQAcAA6AC8ALwBkAHIAbQAuAGMAYQBuAGEAbAAtAHAAbAB1AHMALgBjAG8AbQAvADwALwBMAEEAXwBVAFIATAA+ADwATABVAEkAXwBVAFIATAA+AGgAdAB0AHAAOgAvAC8AZAByAG0ALgBjAGEAbgBhAGwALQBwAGwAdQBzAC4AYwBvAG0ALwA8AC8ATABVAEkAXwBVAFIATAA+ADwARABTAF8ASQBEAD4AeQBZAEkAUABEAEIAYwBhADEAawBtAE0AZgBMADYAMABJAHMAZgBnAEEAUQA9AD0APAAvAEQAUwBfAEkARAA+ADwAQwBVAFMAVABPAE0AQQBUAFQAUgBJAEIAVQBUAEUAUwAgAHgAbQBsAG4AcwA9ACIAIgA+ADwAZQBuAGMAcgB5AHAAdABpAG8AbgByAGUAZgA+ADQANQAwAF8ANAAwADIANABfADIAOQAwADQAMgAwADIAMAAxADQAMwAzADwALwBlAG4AYwByAHkAcAB0AGkAbwBuAHIAZQBmAD4APAAvAEMAVQBTAFQATwBNAEEAVABUAFIASQBCAFUAVABFAFMAPgA8AEMASABFAEMASwBTAFUATQA+AFYATgB6AC8AYQBaAGkAawBFAFYAOAA9ADwALwBDAEgARQBDAEsAUwBVAE0APgA8AC8ARABBAFQAQQA+ADwALwBXAFIATQBIAEUAQQBEAEUAUgA+AA==</PSSH>
      <ContentProtectionData>PGNlbmM6cHNzaD5BQUFENkhCemMyZ0FBQUFBbWdUd2VaaEFRb2Fya3VaYjRJaGZsUUFBQThqSUF3QUFBUUFCQUw0RFBBQlhBRklBVFFCSUFFVUFRUUJFQUVVQVVnQWdBSGdBYlFCc0FHNEFjd0E5QUNJQWFBQjBBSFFBY0FBNkFDOEFMd0J6QUdNQWFBQmxBRzBBWVFCekFDNEFiUUJwQUdNQWNnQnZBSE1BYndCbUFIUUFMZ0JqQUc4QWJRQXZBRVFBVWdCTkFDOEFNZ0F3QURBQU53QXZBREFBTXdBdkFGQUFiQUJoQUhrQVVnQmxBR0VBWkFCNUFFZ0FaUUJoQUdRQVpRQnlBQ0lBSUFCMkFHVUFjZ0J6QUdrQWJ3QnVBRDBBSWdBMEFDNEFNQUF1QURBQUxnQXdBQ0lBUGdBOEFFUUFRUUJVQUVFQVBnQThBRkFBVWdCUEFGUUFSUUJEQUZRQVNRQk9BRVlBVHdBK0FEd0FTd0JGQUZrQVRBQkZBRTRBUGdBeEFEWUFQQUF2QUVzQVJRQlpBRXdBUlFCT0FENEFQQUJCQUV3QVJ3QkpBRVFBUGdCQkFFVUFVd0JEQUZRQVVnQThBQzhBUVFCTUFFY0FTUUJFQUQ0QVBBQXZBRkFBVWdCUEFGUUFSUUJEQUZRQVNRQk9BRVlBVHdBK0FEd0FTd0JKQUVRQVBnQk5BR2tBZUFCckFFb0FUQUJHQUV3QWRBQXdBRmNBV2dCREFEUUFNd0JQQUZRQVZBQjNBRTBBUVFCbkFEMEFQUUE4QUM4QVN3QkpBRVFBUGdBOEFFd0FRUUJmQUZVQVVnQk1BRDRBYUFCMEFIUUFjQUE2QUM4QUx3QmtBSElBYlFBdUFHTUFZUUJ1QUdFQWJBQXRBSEFBYkFCMUFITUFMZ0JqQUc4QWJRQXZBRHdBTHdCTUFFRUFYd0JWQUZJQVRBQStBRHdBVEFCVkFFa0FYd0JWQUZJQVRBQStBR2dBZEFCMEFIQUFPZ0F2QUM4QVpBQnlBRzBBTGdCakFHRUFiZ0JoQUd3QUxRQndBR3dBZFFCekFDNEFZd0J2QUcwQUx3QThBQzhBVEFCVkFFa0FYd0JWQUZJQVRBQStBRHdBUkFCVEFGOEFTUUJFQUQ0QWVRQlpBRWtBVUFCRUFFSUFZd0JoQURFQWF3QnRBRTBBWmdCTUFEWUFNQUJKQUhNQVpnQm5BRUVBVVFBOUFEMEFQQUF2QUVRQVV3QmZBRWtBUkFBK0FEd0FRd0JWQUZNQVZBQlBBRTBBUVFCVUFGUUFVZ0JKQUVJQVZRQlVBRVVBVXdBZ0FIZ0FiUUJzQUc0QWN3QTlBQ0lBSWdBK0FEd0FaUUJ1QUdNQWNnQjVBSEFBZEFCcEFHOEFiZ0J5QUdVQVpnQStBRFFBTlFBd0FGOEFOQUF3QURJQU5BQmZBRElBT1FBd0FEUUFNZ0F3QURJQU1BQXhBRFFBTXdBekFEd0FMd0JsQUc0QVl3QnlBSGtBY0FCMEFHa0Fid0J1QUhJQVpRQm1BRDRBUEFBdkFFTUFWUUJUQUZRQVR3Qk5BRUVBVkFCVUFGSUFTUUJDQUZVQVZBQkZBRk1BUGdBOEFFTUFTQUJGQUVNQVN3QlRBRlVBVFFBK0FGWUFUZ0I2QUM4QVlRQmFBR2tBYXdCRkFGWUFPQUE5QUR3QUx3QkRBRWdBUlFCREFFc0FVd0JWQUUwQVBnQThBQzhBUkFCQkFGUUFRUUErQUR3QUx3QlhBRklBVFFCSUFFVUFRUUJFQUVVQVVnQStBQT09PC9jZW5jOnBzc2g+PG1zcHI6cHJvPnlBTUFBQUVBQVFDK0F6d0FWd0JTQUUwQVNBQkZBRUVBUkFCRkFGSUFJQUI0QUcwQWJBQnVBSE1BUFFBaUFHZ0FkQUIwQUhBQU9nQXZBQzhBY3dCakFHZ0FaUUJ0QUdFQWN3QXVBRzBBYVFCakFISUFid0J6QUc4QVpnQjBBQzRBWXdCdkFHMEFMd0JFQUZJQVRRQXZBRElBTUFBd0FEY0FMd0F3QURNQUx3QlFBR3dBWVFCNUFGSUFaUUJoQUdRQWVRQklBR1VBWVFCa0FHVUFjZ0FpQUNBQWRnQmxBSElBY3dCcEFHOEFiZ0E5QUNJQU5BQXVBREFBTGdBd0FDNEFNQUFpQUQ0QVBBQkVBRUVBVkFCQkFENEFQQUJRQUZJQVR3QlVBRVVBUXdCVUFFa0FUZ0JHQUU4QVBnQThBRXNBUlFCWkFFd0FSUUJPQUQ0QU1RQTJBRHdBTHdCTEFFVUFXUUJNQUVVQVRnQStBRHdBUVFCTUFFY0FTUUJFQUQ0QVFRQkZBRk1BUXdCVUFGSUFQQUF2QUVFQVRBQkhBRWtBUkFBK0FEd0FMd0JRQUZJQVR3QlVBRVVBUXdCVUFFa0FUZ0JHQUU4QVBnQThBRXNBU1FCRUFENEFUUUJwQUhnQWF3QktBRXdBUmdCTUFIUUFNQUJYQUZvQVF3QTBBRE1BVHdCVUFGUUFkd0JOQUVFQVp3QTlBRDBBUEFBdkFFc0FTUUJFQUQ0QVBBQk1BRUVBWHdCVkFGSUFUQUErQUdnQWRBQjBBSEFBT2dBdkFDOEFaQUJ5QUcwQUxnQmpBR0VBYmdCaEFHd0FMUUJ3QUd3QWRRQnpBQzRBWXdCdkFHMEFMd0E4QUM4QVRBQkJBRjhBVlFCU0FFd0FQZ0E4QUV3QVZRQkpBRjhBVlFCU0FFd0FQZ0JvQUhRQWRBQndBRG9BTHdBdkFHUUFjZ0J0QUM0QVl3QmhBRzRBWVFCc0FDMEFjQUJzQUhVQWN3QXVBR01BYndCdEFDOEFQQUF2QUV3QVZRQkpBRjhBVlFCU0FFd0FQZ0E4QUVRQVV3QmZBRWtBUkFBK0FIa0FXUUJKQUZBQVJBQkNBR01BWVFBeEFHc0FiUUJOQUdZQVRBQTJBREFBU1FCekFHWUFad0JCQUZFQVBRQTlBRHdBTHdCRUFGTUFYd0JKQUVRQVBnQThBRU1BVlFCVEFGUUFUd0JOQUVFQVZBQlVBRklBU1FCQ0FGVUFWQUJGQUZNQUlBQjRBRzBBYkFCdUFITUFQUUFpQUNJQVBnQThBR1VBYmdCakFISUFlUUJ3QUhRQWFRQnZBRzRBY2dCbEFHWUFQZ0EwQURVQU1BQmZBRFFBTUFBeUFEUUFYd0F5QURrQU1BQTBBRElBTUFBeUFEQUFNUUEwQURNQU13QThBQzhBWlFCdUFHTUFjZ0I1QUhBQWRBQnBBRzhBYmdCeUFHVUFaZ0ErQUR3QUx3QkRBRlVBVXdCVUFFOEFUUUJCQUZRQVZBQlNBRWtBUWdCVkFGUUFSUUJUQUQ0QVBBQkRBRWdBUlFCREFFc0FVd0JWQUUwQVBnQldBRTRBZWdBdkFHRUFXZ0JwQUdzQVJRQldBRGdBUFFBOEFDOEFRd0JJQUVVQVF3QkxBRk1BVlFCTkFENEFQQUF2QUVRQVFRQlVBRUVBUGdBOEFDOEFWd0JTQUUwQVNBQkZBRUVBUkFCRkFGSUFQZ0E9PC9tc3ByOnBybz4=</ContentProtectionData>
    </DRMSystem>
    <DRMSystem systemId="9a04f079-9840-4286-ab92-e65be0885f95" kid="7ac05713-d010-45d3-8a41-2f90493348bf">
      <PSSH>AAAD6HBzc2gAAAAAmgTweZhAQoarkuZb4IhflQAAA8jIAwAAAQABAL4DPABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBFAFkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APABBAEwARwBJAEQAPgBBAEUAUwBDAFQAUgA8AC8AQQBMAEcASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBJAEQAPgBFADEAZgBBAGUAaABEAFEAMAAwAFcASwBRAFMAKwBRAFMAVABOAEkAdgB3AD0APQA8AC8ASwBJAEQAPgA8AEwAQQBfAFUAUgBMAD4AaAB0AHQAcAA6AC8ALwBkAHIAbQAuAGMAYQBuAGEAbAAtAHAAbAB1AHMALgBjAG8AbQAvADwALwBMAEEAXwBVAFIATAA+ADwATABVAEkAXwBVAFIATAA+AGgAdAB0AHAAOgAvAC8AZAByAG0ALgBjAGEAbgBhAGwALQBwAGwAdQBzAC4AYwBvAG0ALwA8AC8ATABVAEkAXwBVAFIATAA+ADwARABTAF8ASQBEAD4AeQBZAEkAUABEAEIAYwBhADEAawBtAE0AZgBMADYAMABJAHMAZgBnAEEAUQA9AD0APAAvAEQAUwBfAEkARAA+ADwAQwBVAFMAVABPAE0AQQBUAFQAUgBJAEIAVQBUAEUAUwAgAHgAbQBsAG4AcwA9ACIAIgA+ADwAZQBuAGMAcgB5AHAAdABpAG8AbgByAGUAZgA+ADQANQAwAF8ANAAwADIANABfADIAOQAwADQAMgAwADIAMAAxADQAMwAzADwALwBlAG4AYwByAHkAcAB0AGkAbwBuAHIAZQBmAD4APAAvAEMAVQBTAFQATwBNAEEAVABUAFIASQBCAFUAVABFAFMAPgA8AEMASABFAEMASwBTAFUATQA+AGIAUAA0AHQAcwBZAEcAVABaADYAWQA9ADwALwBDAEgARQBDAEsAUwBVAE0APgA8AC8ARABBAFQAQQA+ADwALwBXAFIATQBIAEUAQQBEAEUAUgA+AA==</PSSH>
      <ContentProtectionData>PGNlbmM6cHNzaD5BQUFENkhCemMyZ0FBQUFBbWdUd2VaaEFRb2Fya3VaYjRJaGZsUUFBQThqSUF3QUFBUUFCQUw0RFBBQlhBRklBVFFCSUFFVUFRUUJFQUVVQVVnQWdBSGdBYlFCc0FHNEFjd0E5QUNJQWFBQjBBSFFBY0FBNkFDOEFMd0J6QUdNQWFBQmxBRzBBWVFCekFDNEFiUUJwQUdNQWNnQnZBSE1BYndCbUFIUUFMZ0JqQUc4QWJRQXZBRVFBVWdCTkFDOEFNZ0F3QURBQU53QXZBREFBTXdBdkFGQUFiQUJoQUhrQVVnQmxBR0VBWkFCNUFFZ0FaUUJoQUdRQVpRQnlBQ0lBSUFCMkFHVUFjZ0J6QUdrQWJ3QnVBRDBBSWdBMEFDNEFNQUF1QURBQUxnQXdBQ0lBUGdBOEFFUUFRUUJVQUVFQVBnQThBRkFBVWdCUEFGUUFSUUJEQUZRQVNRQk9BRVlBVHdBK0FEd0FTd0JGQUZrQVRBQkZBRTRBUGdBeEFEWUFQQUF2QUVzQVJRQlpBRXdBUlFCT0FENEFQQUJCQUV3QVJ3QkpBRVFBUGdCQkFFVUFVd0JEQUZRQVVnQThBQzhBUVFCTUFFY0FTUUJFQUQ0QVBBQXZBRkFBVWdCUEFGUUFSUUJEQUZRQVNRQk9BRVlBVHdBK0FEd0FTd0JKQUVRQVBnQkZBREVBWmdCQkFHVUFhQUJFQUZFQU1BQXdBRmNBU3dCUkFGTUFLd0JSQUZNQVZBQk9BRWtBZGdCM0FEMEFQUUE4QUM4QVN3QkpBRVFBUGdBOEFFd0FRUUJmQUZVQVVnQk1BRDRBYUFCMEFIUUFjQUE2QUM4QUx3QmtBSElBYlFBdUFHTUFZUUJ1QUdFQWJBQXRBSEFBYkFCMUFITUFMZ0JqQUc4QWJRQXZBRHdBTHdCTUFFRUFYd0JWQUZJQVRBQStBRHdBVEFCVkFFa0FYd0JWQUZJQVRBQStBR2dBZEFCMEFIQUFPZ0F2QUM4QVpBQnlBRzBBTGdCakFHRUFiZ0JoQUd3QUxRQndBR3dBZFFCekFDNEFZd0J2QUcwQUx3QThBQzhBVEFCVkFFa0FYd0JWQUZJQVRBQStBRHdBUkFCVEFGOEFTUUJFQUQ0QWVRQlpBRWtBVUFCRUFFSUFZd0JoQURFQWF3QnRBRTBBWmdCTUFEWUFNQUJKQUhNQVpnQm5BRUVBVVFBOUFEMEFQQUF2QUVRQVV3QmZBRWtBUkFBK0FEd0FRd0JWQUZNQVZBQlBBRTBBUVFCVUFGUUFVZ0JKQUVJQVZRQlVBRVVBVXdBZ0FIZ0FiUUJzQUc0QWN3QTlBQ0lBSWdBK0FEd0FaUUJ1QUdNQWNnQjVBSEFBZEFCcEFHOEFiZ0J5QUdVQVpnQStBRFFBTlFBd0FGOEFOQUF3QURJQU5BQmZBRElBT1FBd0FEUUFNZ0F3QURJQU1BQXhBRFFBTXdBekFEd0FMd0JsQUc0QVl3QnlBSGtBY0FCMEFHa0Fid0J1QUhJQVpRQm1BRDRBUEFBdkFFTUFWUUJUQUZRQVR3Qk5BRUVBVkFCVUFGSUFTUUJDQUZVQVZBQkZBRk1BUGdBOEFFTUFTQUJGQUVNQVN3QlRBRlVBVFFBK0FHSUFVQUEwQUhRQWN3QlpBRWNBVkFCYUFEWUFXUUE5QUR3QUx3QkRBRWdBUlFCREFFc0FVd0JWQUUwQVBnQThBQzhBUkFCQkFGUUFRUUErQUR3QUx3QlhBRklBVFFCSUFFVUFRUUJFQUVVQVVnQStBQT09PC9jZW5jOnBzc2g+PG1zcHI6cHJvPnlBTUFBQUVBQVFDK0F6d0FWd0JTQUUwQVNBQkZBRUVBUkFCRkFGSUFJQUI0QUcwQWJBQnVBSE1BUFFBaUFHZ0FkQUIwQUhBQU9nQXZBQzhBY3dCakFHZ0FaUUJ0QUdFQWN3QXVBRzBBYVFCakFISUFid0J6QUc4QVpnQjBBQzRBWXdCdkFHMEFMd0JFQUZJQVRRQXZBRElBTUFBd0FEY0FMd0F3QURNQUx3QlFBR3dBWVFCNUFGSUFaUUJoQUdRQWVRQklBR1VBWVFCa0FHVUFjZ0FpQUNBQWRnQmxBSElBY3dCcEFHOEFiZ0E5QUNJQU5BQXVBREFBTGdBd0FDNEFNQUFpQUQ0QVBBQkVBRUVBVkFCQkFENEFQQUJRQUZJQVR3QlVBRVVBUXdCVUFFa0FUZ0JHQUU4QVBnQThBRXNBUlFCWkFFd0FSUUJPQUQ0QU1RQTJBRHdBTHdCTEFFVUFXUUJNQUVVQVRnQStBRHdBUVFCTUFFY0FTUUJFQUQ0QVFRQkZBRk1BUXdCVUFGSUFQQUF2QUVFQVRBQkhBRWtBUkFBK0FEd0FMd0JRQUZJQVR3QlVBRVVBUXdCVUFFa0FUZ0JHQUU4QVBnQThBRXNBU1FCRUFENEFSUUF4QUdZQVFRQmxBR2dBUkFCUkFEQUFNQUJYQUVzQVVRQlRBQ3NBVVFCVEFGUUFUZ0JKQUhZQWR3QTlBRDBBUEFBdkFFc0FTUUJFQUQ0QVBBQk1BRUVBWHdCVkFGSUFUQUErQUdnQWRBQjBBSEFBT2dBdkFDOEFaQUJ5QUcwQUxnQmpBR0VBYmdCaEFHd0FMUUJ3QUd3QWRRQnpBQzRBWXdCdkFHMEFMd0E4QUM4QVRBQkJBRjhBVlFCU0FFd0FQZ0E4QUV3QVZRQkpBRjhBVlFCU0FFd0FQZ0JvQUhRQWRBQndBRG9BTHdBdkFHUUFjZ0J0QUM0QVl3QmhBRzRBWVFCc0FDMEFjQUJzQUhVQWN3QXVBR01BYndCdEFDOEFQQUF2QUV3QVZRQkpBRjhBVlFCU0FFd0FQZ0E4QUVRQVV3QmZBRWtBUkFBK0FIa0FXUUJKQUZBQVJBQkNBR01BWVFBeEFHc0FiUUJOQUdZQVRBQTJBREFBU1FCekFHWUFad0JCQUZFQVBRQTlBRHdBTHdCRUFGTUFYd0JKQUVRQVBnQThBRU1BVlFCVEFGUUFUd0JOQUVFQVZBQlVBRklBU1FCQ0FGVUFWQUJGQUZNQUlBQjRBRzBBYkFCdUFITUFQUUFpQUNJQVBnQThBR1VBYmdCakFISUFlUUJ3QUhRQWFRQnZBRzRBY2dCbEFHWUFQZ0EwQURVQU1BQmZBRFFBTUFBeUFEUUFYd0F5QURrQU1BQTBBRElBTUFBeUFEQUFNUUEwQURNQU13QThBQzhBWlFCdUFHTUFjZ0I1QUhBQWRBQnBBRzhBYmdCeUFHVUFaZ0ErQUR3QUx3QkRBRlVBVXdCVUFFOEFUUUJCQUZRQVZBQlNBRWtBUWdCVkFGUUFSUUJUQUQ0QVBBQkRBRWdBUlFCREFFc0FVd0JWQUUwQVBnQmlBRkFBTkFCMEFITUFXUUJIQUZRQVdnQTJBRmtBUFFBOEFDOEFRd0JJQUVVQVF3QkxBRk1BVlFCTkFENEFQQUF2QUVRQVFRQlVBRUVBUGdBOEFDOEFWd0JTQUUwQVNBQkZBRUVBUkFCRkFGSUFQZ0E9PC9tc3ByOnBybz4=</ContentProtectionData>
    </DRMSystem>
    <DRMSystem systemId="9a04f079-9840-4286-ab92-e65be0885f95" kid="6ee8f9a8-0eea-433b-86ee-d343dccfc926">
      <PSSH>AAAD6HBzc2gAAAAAmgTweZhAQoarkuZb4IhflQAAA8jIAwAAAQABAL4DPABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBFAFkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APABBAEwARwBJAEQAPgBBAEUAUwBDAFQAUgA8AC8AQQBMAEcASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBJAEQAPgBxAFAAbgBvAGIAdQBvAE8ATwAwAE8ARwA3AHQATgBEADMATQAvAEoASgBnAD0APQA8AC8ASwBJAEQAPgA8AEwAQQBfAFUAUgBMAD4AaAB0AHQAcAA6AC8ALwBkAHIAbQAuAGMAYQBuAGEAbAAtAHAAbAB1AHMALgBjAG8AbQAvADwALwBMAEEAXwBVAFIATAA+ADwATABVAEkAXwBVAFIATAA+AGgAdAB0AHAAOgAvAC8AZAByAG0ALgBjAGEAbgBhAGwALQBwAGwAdQBzAC4AYwBvAG0ALwA8AC8ATABVAEkAXwBVAFIATAA+ADwARABTAF8ASQBEAD4AeQBZAEkAUABEAEIAYwBhADEAawBtAE0AZgBMADYAMABJAHMAZgBnAEEAUQA9AD0APAAvAEQAUwBfAEkARAA+ADwAQwBVAFMAVABPAE0AQQBUAFQAUgBJAEIAVQBUAEUAUwAgAHgAbQBsAG4AcwA9ACIAIgA+ADwAZQBuAGMAcgB5AHAAdABpAG8AbgByAGUAZgA+ADQANQAwAF8ANAAwADIANABfADIAOQAwADQAMgAwADIAMAAxADQAMwAzADwALwBlAG4AYwByAHkAcAB0AGkAbwBuAHIAZQBmAD4APAAvAEMAVQBTAFQATwBNAEEAVABUAFIASQBCAFUAVABFAFMAPgA8AEMASABFAEMASwBTAFUATQA+AGIAVQA1AGgAVAA1AG4ANgBuAGgAUQA9ADwALwBDAEgARQBDAEsAUwBVAE0APgA8AC8ARABBAFQAQQA+ADwALwBXAFIATQBIAEUAQQBEAEUAUgA+AA==</PSSH>
      <ContentProtectionData>PGNlbmM6cHNzaD5BQUFENkhCemMyZ0FBQUFBbWdUd2VaaEFRb2Fya3VaYjRJaGZsUUFBQThqSUF3QUFBUUFCQUw0RFBBQlhBRklBVFFCSUFFVUFRUUJFQUVVQVVnQWdBSGdBYlFCc0FHNEFjd0E5QUNJQWFBQjBBSFFBY0FBNkFDOEFMd0J6QUdNQWFBQmxBRzBBWVFCekFDNEFiUUJwQUdNQWNnQnZBSE1BYndCbUFIUUFMZ0JqQUc4QWJRQXZBRVFBVWdCTkFDOEFNZ0F3QURBQU53QXZBREFBTXdBdkFGQUFiQUJoQUhrQVVnQmxBR0VBWkFCNUFFZ0FaUUJoQUdRQVpRQnlBQ0lBSUFCMkFHVUFjZ0J6QUdrQWJ3QnVBRDBBSWdBMEFDNEFNQUF1QURBQUxnQXdBQ0lBUGdBOEFFUUFRUUJVQUVFQVBnQThBRkFBVWdCUEFGUUFSUUJEQUZRQVNRQk9BRVlBVHdBK0FEd0FTd0JGQUZrQVRBQkZBRTRBUGdBeEFEWUFQQUF2QUVzQVJRQlpBRXdBUlFCT0FENEFQQUJCQUV3QVJ3QkpBRVFBUGdCQkFFVUFVd0JEQUZRQVVnQThBQzhBUVFCTUFFY0FTUUJFQUQ0QVBBQXZBRkFBVWdCUEFGUUFSUUJEQUZRQVNRQk9BRVlBVHdBK0FEd0FTd0JKQUVRQVBnQnhBRkFBYmdCdkFHSUFkUUJ2QUU4QVR3QXdBRThBUndBM0FIUUFUZ0JFQURNQVRRQXZBRW9BU2dCbkFEMEFQUUE4QUM4QVN3QkpBRVFBUGdBOEFFd0FRUUJmQUZVQVVnQk1BRDRBYUFCMEFIUUFjQUE2QUM4QUx3QmtBSElBYlFBdUFHTUFZUUJ1QUdFQWJBQXRBSEFBYkFCMUFITUFMZ0JqQUc4QWJRQXZBRHdBTHdCTUFFRUFYd0JWQUZJQVRBQStBRHdBVEFCVkFFa0FYd0JWQUZJQVRBQStBR2dBZEFCMEFIQUFPZ0F2QUM4QVpBQnlBRzBBTGdCakFHRUFiZ0JoQUd3QUxRQndBR3dBZFFCekFDNEFZd0J2QUcwQUx3QThBQzhBVEFCVkFFa0FYd0JWQUZJQVRBQStBRHdBUkFCVEFGOEFTUUJFQUQ0QWVRQlpBRWtBVUFCRUFFSUFZd0JoQURFQWF3QnRBRTBBWmdCTUFEWUFNQUJKQUhNQVpnQm5BRUVBVVFBOUFEMEFQQUF2QUVRQVV3QmZBRWtBUkFBK0FEd0FRd0JWQUZNQVZBQlBBRTBBUVFCVUFGUUFVZ0JKQUVJQVZRQlVBRVVBVXdBZ0FIZ0FiUUJzQUc0QWN3QTlBQ0lBSWdBK0FEd0FaUUJ1QUdNQWNnQjVBSEFBZEFCcEFHOEFiZ0J5QUdVQVpnQStBRFFBTlFBd0FGOEFOQUF3QURJQU5BQmZBRElBT1FBd0FEUUFNZ0F3QURJQU1BQXhBRFFBTXdBekFEd0FMd0JsQUc0QVl3QnlBSGtBY0FCMEFHa0Fid0J1QUhJQVpRQm1BRDRBUEFBdkFFTUFWUUJUQUZRQVR3Qk5BRUVBVkFCVUFGSUFTUUJDQUZVQVZBQkZBRk1BUGdBOEFFTUFTQUJGQUVNQVN3QlRBRlVBVFFBK0FHSUFWUUExQUdnQVZBQTFBRzRBTmdCdUFHZ0FVUUE5QUR3QUx3QkRBRWdBUlFCREFFc0FVd0JWQUUwQVBnQThBQzhBUkFCQkFGUUFRUUErQUR3QUx3QlhBRklBVFFCSUFFVUFRUUJFQUVVQVVnQStBQT09PC9jZW5jOnBzc2g+PG1zcHI6cHJvPnlBTUFBQUVBQVFDK0F6d0FWd0JTQUUwQVNBQkZBRUVBUkFCRkFGSUFJQUI0QUcwQWJBQnVBSE1BUFFBaUFHZ0FkQUIwQUhBQU9nQXZBQzhBY3dCakFHZ0FaUUJ0QUdFQWN3QXVBRzBBYVFCakFISUFid0J6QUc4QVpnQjBBQzRBWXdCdkFHMEFMd0JFQUZJQVRRQXZBRElBTUFBd0FEY0FMd0F3QURNQUx3QlFBR3dBWVFCNUFGSUFaUUJoQUdRQWVRQklBR1VBWVFCa0FHVUFjZ0FpQUNBQWRnQmxBSElBY3dCcEFHOEFiZ0E5QUNJQU5BQXVBREFBTGdBd0FDNEFNQUFpQUQ0QVBBQkVBRUVBVkFCQkFENEFQQUJRQUZJQVR3QlVBRVVBUXdCVUFFa0FUZ0JHQUU4QVBnQThBRXNBUlFCWkFFd0FSUUJPQUQ0QU1RQTJBRHdBTHdCTEFFVUFXUUJNQUVVQVRnQStBRHdBUVFCTUFFY0FTUUJFQUQ0QVFRQkZBRk1BUXdCVUFGSUFQQUF2QUVFQVRBQkhBRWtBUkFBK0FEd0FMd0JRQUZJQVR3QlVBRVVBUXdCVUFFa0FUZ0JHQUU4QVBnQThBRXNBU1FCRUFENEFjUUJRQUc0QWJ3QmlBSFVBYndCUEFFOEFNQUJQQUVjQU53QjBBRTRBUkFBekFFMEFMd0JLQUVvQVp3QTlBRDBBUEFBdkFFc0FTUUJFQUQ0QVBBQk1BRUVBWHdCVkFGSUFUQUErQUdnQWRBQjBBSEFBT2dBdkFDOEFaQUJ5QUcwQUxnQmpBR0VBYmdCaEFHd0FMUUJ3QUd3QWRRQnpBQzRBWXdCdkFHMEFMd0E4QUM4QVRBQkJBRjhBVlFCU0FFd0FQZ0E4QUV3QVZRQkpBRjhBVlFCU0FFd0FQZ0JvQUhRQWRBQndBRG9BTHdBdkFHUUFjZ0J0QUM0QVl3QmhBRzRBWVFCc0FDMEFjQUJzQUhVQWN3QXVBR01BYndCdEFDOEFQQUF2QUV3QVZRQkpBRjhBVlFCU0FFd0FQZ0E4QUVRQVV3QmZBRWtBUkFBK0FIa0FXUUJKQUZBQVJBQkNBR01BWVFBeEFHc0FiUUJOQUdZQVRBQTJBREFBU1FCekFHWUFad0JCQUZFQVBRQTlBRHdBTHdCRUFGTUFYd0JKQUVRQVBnQThBRU1BVlFCVEFGUUFUd0JOQUVFQVZBQlVBRklBU1FCQ0FGVUFWQUJGQUZNQUlBQjRBRzBBYkFCdUFITUFQUUFpQUNJQVBnQThBR1VBYmdCakFISUFlUUJ3QUhRQWFRQnZBRzRBY2dCbEFHWUFQZ0EwQURVQU1BQmZBRFFBTUFBeUFEUUFYd0F5QURrQU1BQTBBRElBTUFBeUFEQUFNUUEwQURNQU13QThBQzhBWlFCdUFHTUFjZ0I1QUhBQWRBQnBBRzhBYmdCeUFHVUFaZ0ErQUR3QUx3QkRBRlVBVXdCVUFFOEFUUUJCQUZRQVZBQlNBRWtBUWdCVkFGUUFSUUJUQUQ0QVBBQkRBRWdBUlFCREFFc0FVd0JWQUUwQVBnQmlBRlVBTlFCb0FGUUFOUUJ1QURZQWJnQm9BRkVBUFFBOEFDOEFRd0JJQUVVQVF3QkxBRk1BVlFCTkFENEFQQUF2QUVRQVFRQlVBRUVBUGdBOEFDOEFWd0JTQUUwQVNBQkZBRUVBUkFCRkFGSUFQZ0E9PC9tc3ByOnBybz4=</ContentProtectionData>
    </DRMSystem>
    <DRMSystem systemId="edef8ba9-79d6-4ace-a3c8-27dcd51d21ed" kid="04efba97-7fb9-4401-ad0d-1fd656aa3a17">
      <PSSH>AAAAW3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAADsIARIQBO+6l3+5RAGtDR/WVqo6FxoIV2lkZXZpbmUiFTQ1MF80MDI0XzI5MDQyMDIwMTQzM0jj3JWbBg==</PSSH>
      <ContentProtectionData>PGNlbmM6cHNzaD5BQUFBVzNCemMyZ0FBQUFBN2UrTHFYbldTczZqeUNmYzFSMGg3UUFBQURzSUFSSVFCTys2bDMrNVJBR3REUi9XVnFvNkZ4b0lWMmxrWlhacGJtVWlGVFExTUY4ME1ESTBYekk1TURReU1ESXdNVFF6TTBqajNKV2JCZz09PC9jZW5jOnBzc2g+</ContentProtectionData>
    </DRMSystem>
    <DRMSystem systemId="edef8ba9-79d6-4ace-a3c8-27dcd51d21ed" kid="24642c32-4bb1-45b7-990b-8dce4d3c0c02">
      <PSSH>AAAAW3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAADsIARIQJGQsMkuxRbeZC43OTTwMAhoIV2lkZXZpbmUiFTQ1MF80MDI0XzI5MDQyMDIwMTQzM0jj3JWbBg==</PSSH>
      <ContentProtectionData>PGNlbmM6cHNzaD5BQUFBVzNCemMyZ0FBQUFBN2UrTHFYbldTczZqeUNmYzFSMGg3UUFBQURzSUFSSVFKR1FzTWt1eFJiZVpDNDNPVFR3TUFob0lWMmxrWlhacGJtVWlGVFExTUY4ME1ESTBYekk1TURReU1ESXdNVFF6TTBqajNKV2JCZz09PC9jZW5jOnBzc2g+</ContentProtectionData>
    </DRMSystem>
    <DRMSystem systemId="edef8ba9-79d6-4ace-a3c8-27dcd51d21ed" kid="7ac05713-d010-45d3-8a41-2f90493348bf">
      <PSSH>AAAAW3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAADsIARIQesBXE9AQRdOKQS+QSTNIvxoIV2lkZXZpbmUiFTQ1MF80MDI0XzI5MDQyMDIwMTQzM0jj3JWbBg==</PSSH>
      <ContentProtectionData>PGNlbmM6cHNzaD5BQUFBVzNCemMyZ0FBQUFBN2UrTHFYbldTczZqeUNmYzFSMGg3UUFBQURzSUFSSVFlc0JYRTlBUVJkT0tRUytRU1ROSXZ4b0lWMmxrWlhacGJtVWlGVFExTUY4ME1ESTBYekk1TURReU1ESXdNVFF6TTBqajNKV2JCZz09PC9jZW5jOnBzc2g+</ContentProtectionData>
    </DRMSystem>
    <DRMSystem systemId="edef8ba9-79d6-4ace-a3c8-27dcd51d21ed" kid="6ee8f9a8-0eea-433b-86ee-d343dccfc926">
      <PSSH>AAAAW3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAADsIARIQbuj5qA7qQzuG7tND3M/JJhoIV2lkZXZpbmUiFTQ1MF80MDI0XzI5MDQyMDIwMTQzM0jj3JWbBg==</PSSH>
      <ContentProtectionData>PGNlbmM6cHNzaD5BQUFBVzNCemMyZ0FBQUFBN2UrTHFYbldTczZqeUNmYzFSMGg3UUFBQURzSUFSSVFidWo1cUE3cVF6dUc3dE5EM00vSkpob0lWMmxrWlhacGJtVWlGVFExTUY4ME1ESTBYekk1TURReU1ESXdNVFF6TTBqajNKV2JCZz09PC9jZW5jOnBzc2g+</ContentProtectionData>
    </DRMSystem>
    <DRMSystem systemId="adb41c24-2dbf-4a6d-958b-4457c0d27b95" kid="04efba97-7fb9-4401-ad0d-1fd656aa3a17">
      <PSSH>AAAAkHBzc2gAAAAArbQcJC2/Sm2Vi0RXwNJ7lQAAAHBleUpqYjI1MFpXNTBTV1FpT2lJME5UQmZOREF5TkY4eU9UQTBNakF5TURFME16TWlMQ0pyWlhsSlpDSTZJakEwWldaaVlUazNMVGRtWWprdE5EUXdNUzFoWkRCa0xURm1aRFkxTm1GaE0yRXhOeUo5</PSSH>
      <ContentProtectionData>PGNlbmM6cHNzaD5BQUFBa0hCemMyZ0FBQUFBcmJRY0pDMi9TbTJWaTBSWHdOSjdsUUFBQUhCbGVVcHFZakkxTUZwWE5UQlRWMUZwVDJsSk1FNVVRbVpPUkVGNVRrWTRlVTlVUVRCTmFrRjVUVVJGTUUxNlRXbE1RMHB5V2xoc1NscERTVFpKYWtFd1dsZGFhVmxVYXpOTVZHUnRXV3ByZEU1RVVYZE5VekZvV2tSQ2EweFVSbTFhUkZreFRtMUdhRTB5UlhoT2VVbzU8L2NlbmM6cHNzaD4=</ContentProtectionData>
    </DRMSystem>
    <DRMSystem systemId="adb41c24-2dbf-4a6d-958b-4457c0d27b95" kid="24642c32-4bb1-45b7-990b-8dce4d3c0c02">
      <PSSH>AAAAkHBzc2gAAAAArbQcJC2/Sm2Vi0RXwNJ7lQAAAHBleUpqYjI1MFpXNTBTV1FpT2lJME5UQmZOREF5TkY4eU9UQTBNakF5TURFME16TWlMQ0pyWlhsSlpDSTZJakkwTmpReVl6TXlMVFJpWWpFdE5EVmlOeTA1T1RCaUxUaGtZMlUwWkROak1HTXdNaUo5</PSSH>
      <ContentProtectionData>PGNlbmM6cHNzaD5BQUFBa0hCemMyZ0FBQUFBcmJRY0pDMi9TbTJWaTBSWHdOSjdsUUFBQUhCbGVVcHFZakkxTUZwWE5UQlRWMUZwVDJsSk1FNVVRbVpPUkVGNVRrWTRlVTlVUVRCTmFrRjVUVVJGTUUxNlRXbE1RMHB5V2xoc1NscERTVFpKYWtrd1RtcFJlVmw2VFhsTVZGSnBXV3BGZEU1RVZtbE9lVEExVDFSQ2FVeFVhR3RaTWxVd1drUk9hazFIVFhkTmFVbzU8L2NlbmM6cHNzaD4=</ContentProtectionData>
    </DRMSystem>
    <DRMSystem systemId="adb41c24-2dbf-4a6d-958b-4457c0d27b95" kid="7ac05713-d010-45d3-8a41-2f90493348bf">
      <PSSH>AAAAkHBzc2gAAAAArbQcJC2/Sm2Vi0RXwNJ7lQAAAHBleUpqYjI1MFpXNTBTV1FpT2lJME5UQmZOREF5TkY4eU9UQTBNakF5TURFME16TWlMQ0pyWlhsSlpDSTZJamRoWXpBMU56RXpMV1F3TVRBdE5EVmtNeTA0WVRReExUSm1PVEEwT1RNek5EaGlaaUo5</PSSH>
      <ContentProtectionData>PGNlbmM6cHNzaD5BQUFBa0hCemMyZ0FBQUFBcmJRY0pDMi9TbTJWaTBSWHdOSjdsUUFBQUhCbGVVcHFZakkxTUZwWE5UQlRWMUZwVDJsSk1FNVVRbVpPUkVGNVRrWTRlVTlVUVRCTmFrRjVUVVJGTUUxNlRXbE1RMHB5V2xoc1NscERTVFpKYW1Sb1dYcEJNVTU2UlhwTVYxRjNUVlJCZEU1RVZtdE5lVEEwV1ZSUmVFeFVTbTFQVkVFd1QxUk5lazVFYUdsYWFVbzU8L2NlbmM6cHNzaD4=</ContentProtectionData>
    </DRMSystem>
    <DRMSystem systemId="adb41c24-2dbf-4a6d-958b-4457c0d27b95" kid="6ee8f9a8-0eea-433b-86ee-d343dccfc926">
      <PSSH>AAAAkHBzc2gAAAAArbQcJC2/Sm2Vi0RXwNJ7lQAAAHBleUpqYjI1MFpXNTBTV1FpT2lJME5UQmZOREF5TkY4eU9UQTBNakF5TURFME16TWlMQ0pyWlhsSlpDSTZJalpsWlRobU9XRTRMVEJsWldFdE5ETXpZaTA0Tm1WbExXUXpORE5rWTJObVl6a3lOaUo5</PSSH>
      <ContentProtectionData>PGNlbmM6cHNzaD5BQUFBa0hCemMyZ0FBQUFBcmJRY0pDMi9TbTJWaTBSWHdOSjdsUUFBQUhCbGVVcHFZakkxTUZwWE5UQlRWMUZwVDJsSk1FNVVRbVpPUkVGNVRrWTRlVTlVUVRCTmFrRjVUVVJGTUUxNlRXbE1RMHB5V2xoc1NscERTVFpKYWxwc1dsUm9iVTlYUlRSTVZFSnNXbGRGZEU1RVRYcFphVEEwVG0xV2JFeFhVWHBPUkU1cldUSk9iVmw2YTNsT2FVbzU8L2NlbmM6cHNzaD4=</ContentProtectionData>
    </DRMSystem>
    <DRMSystem systemId="94ce86fb-2dbf-4a6d-958b-4457c0d27b95" kid="04efba97-7fb9-4401-ad0d-1fd656aa3a17">
      <HLSSignalingData>I0VYVC1YLUtFWTpNRVRIT0Q9QUVTLTEyOCxVUkk9Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MS9rZXkva2V5Igo=</HLSSignalingData>
    </DRMSystem>
    <DRMSystem systemId="94ce86fb-2dbf-4a6d-958b-4457c0d27b95" kid="24642c32-4bb1-45b7-990b-8dce4d3c0c02">
      <HLSSignalingData>I0VYVC1YLUtFWTpNRVRIT0Q9QUVTLTEyOCxVUkk9Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MS9rZXkva2V5Igo=</HLSSignalingData>
    </DRMSystem>
    <DRMSystem systemId="94ce86fb-2dbf-4a6d-958b-4457c0d27b95" kid="7ac05713-d010-45d3-8a41-2f90493348bf">
      <HLSSignalingData>I0VYVC1YLUtFWTpNRVRIT0Q9QUVTLTEyOCxVUkk9Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MS9rZXkva2V5Igo=</HLSSignalingData>
    </DRMSystem>
    <DRMSystem systemId="94ce86fb-2dbf-4a6d-958b-4457c0d27b95" kid="6ee8f9a8-0eea-433b-86ee-d343dccfc926">
      <HLSSignalingData>I0VYVC1YLUtFWTpNRVRIT0Q9QUVTLTEyOCxVUkk9Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MS9rZXkva2V5Igo=</HLSSignalingData>
    </DRMSystem>
    <DRMSystem systemId="be58615b-19c4-4684-88b3-c8c57e99e957" kid="04efba97-7fb9-4401-ad0d-1fd656aa3a17">
      <HLSSignalingData>I0VYVC1YLUtFWTpNRVRIT0Q9U0FNUExFLUFFUyxVUkk9Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MS9rZXkva2V5Igo=</HLSSignalingData>
    </DRMSystem>
    <DRMSystem systemId="be58615b-19c4-4684-88b3-c8c57e99e957" kid="24642c32-4bb1-45b7-990b-8dce4d3c0c02">
      <HLSSignalingData>I0VYVC1YLUtFWTpNRVRIT0Q9U0FNUExFLUFFUyxVUkk9Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MS9rZXkva2V5Igo=</HLSSignalingData>
    </DRMSystem>
    <DRMSystem systemId="be58615b-19c4-4684-88b3-c8c57e99e957" kid="7ac05713-d010-45d3-8a41-2f90493348bf">
      <HLSSignalingData>I0VYVC1YLUtFWTpNRVRIT0Q9U0FNUExFLUFFUyxVUkk9Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MS9rZXkva2V5Igo=</HLSSignalingData>
    </DRMSystem>
    <DRMSystem systemId="be58615b-19c4-4684-88b3-c8c57e99e957" kid="6ee8f9a8-0eea-433b-86ee-d343dccfc926">
      <HLSSignalingData>I0VYVC1YLUtFWTpNRVRIT0Q9U0FNUExFLUFFUyxVUkk9Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MS9rZXkva2V5Igo=</HLSSignalingData>
    </DRMSystem>
  </DRMSystemList>
  <ContentKeyUsageRuleList>
    <ContentKeyUsageRule kid="6ee8f9a8-0eea-433b-86ee-d343dccfc926" intendedTrackType="SD">
      <VideoFilter maxPixels="520000"/>
    </ContentKeyUsageRule>
    <ContentKeyUsageRule kid="04efba97-7fb9-4401-ad0d-1fd656aa3a17" intendedTrackType="HD">
      <VideoFilter minPixels="520001" maxPixels="921600"/>
    </ContentKeyUsageRule>
    <ContentKeyUsageRule kid="24642c32-4bb1-45b7-990b-8dce4d3c0c02" intendedTrackType="FHD">
      <VideoFilter minPixels="921601" maxPixels="2073600"/>
    </ContentKeyUsageRule>
    <ContentKeyUsageRule kid="7ac05713-d010-45d3-8a41-2f90493348bf" intendedTrackType="AUDIO">
      <AudioFilter/>
    </ContentKeyUsageRule>
  </ContentKeyUsageRuleList>
</CPIX>
"""

scrambling_Conf = [
    {
        "name": "_default",
        "value": {
            "cencFixed": {
                "keyId": "D4F2DE84F06011EB91FAB67C36D76FBA",
                "key": "12345678901234567890123456789012",
                "contentProtection": 'schemeIdUri="urn:uuid:e2719d58-a985-b3c9-781a-b030af78d30e" value="ClearKey1.0"',
                "pssh": b"\x00\x00\x00 pssh\x00\x00\x00\x00\xe2q\x9dX\xa9\x85\xb3\xc9x\x1a\xb00\xafx\xd3\x0e\x00\x00\x00\x00",
            },
            "cpix": {
                "serverName": "warehouse",
                "cpixId": "scrambling.cpix",
            },
            "smoothFixed": {
                "keyId": "66306c66-096d-4b85-9f64-e5dd17cde172",
                "keySeed": "XVBovsmzhP9gRIZxWfFta3VVRPzVEWmJsazEJ46J",
                "serverUrl": "http://playready.directtaps.net/pr/svc/rightsmanager.asmx",
            },
        },
    },
]

if os.getenv("CLEAR_CONF") == "1":
    print("Removing vod...")

    listjobs = cl.List_vod_jobs(None, None, None, 1000)
    for job in listjobs:
        try:
            cl.Cancel_vod_job(job)
            print(f"Canceling VOD job {job}")
        except:
            print(f"Error during deleting job {vod}")

    listvod = cl.List_vod_assets(None, None, None, 1000)
    while len(listvod) != 0:
        for vod in listvod:
            try:
                cl.Delete_vod_asset(vod)
                print(f"Deleting VOD asset {vod}")
            except:
                print(f"Error during deleting {vod}")
        listvod = cl.List_vod_assets(None, None, None, 1000)

    print("Removing npvr...")
    listnpvr = cl.List_npvrs(None, None, None, 1000)
    while len(listnpvr) != 0:
        for n in listnpvr:
            try:
                cl.Delete_npvr(n)
                print(f"Deleting nPVR {n}")
            except:
                print(f"Error during deleting {n}")
        listnpvr = cl.List_npvrs(None, None, None, 1000)

    print("Removing channels...")
    listChannel = cl.List_live_channels()
    # while len(listChannel) != 0:
    for c in listChannel:
        print(f"Deleting channel {c}")
        try:
            cl.Delete_live_channel(c)
        except Exception as e:
            print(f"Error during deleting {c}")
        # listChannel = cl.List_live_channels()

    print("Removing CPIX server...")
    latest_server_to_delete = None
    for server_name in cl.List_scrambling_servers():
        props = cl.Get_scrambling_server_props(server_name)
        if props["conf"]["isDefault"]:
            latest_server_to_delete = server_name
        else:
            cl.Delete_scrambling_server_conf(server_name)
    if latest_server_to_delete:
        cl.Delete_scrambling_server_conf(latest_server_to_delete)

    print("Deleting SA/SAF...")
    for saf in cl.List_stream_adaptation_families():
        cl.Delete_stream_adaptation_family(saf)
    for sa in cl.List_stream_adaptations():
        cl.Delete_stream_adaptation(sa)

if os.getenv("CREATE_CPIX_SERVER") == "1":
    print("Creating CPIX server...")
    cl.Set_scrambling_server_conf(
        "warehouse",
        {
            "type": "cpix",
            "isDefault": True,
            "serverUrl": f"http://{server_url}/warehouse",
        },
    )

    print("Put CPIX file scrambling.cpix in the warehouse...")
    cpix = tempfile.NamedTemporaryFile(buffering=0)
    cpix.write(cpix_file.encode())
    subprocess.run(
        [
            "scp",
            cpix.name,
            f"amaint@{server_url_without_port}:/var/www/warehouse/scrambling.cpix",
        ]
    )
    subprocess.run(
        [
            "ssh",
            f"amaint@{server_url_without_port}",
            "chmod",
            "o+r",
            "/var/www/warehouse/scrambling.cpix",
        ]
    )
    cpix.close()


if os.getenv("CREATE_SA_SAF") == "1":
    print("Creating SA/SAF...")
    # SA

    if SCRAMBLING:
        # Scrambling
        cl.Set_stream_adaptation_conf(
            "cmaf_scr",
            {
                "outputFormat": "cmaf",
                "subtitlesFormat": "imsc1",
                "chunkDuration": 2,
                "liveWindowDuration": LIVE_WIN_LGTH,
                "scramblingType": "cpix",
            },
        )
        cl.Set_stream_adaptation_conf(
            "dash_number_scr",
            {
                "outputFormat": "dash",
                "subtitlesFormat": "ttmlpassthrough",
                "mpdTemplateType": "number",
                "chunkDuration": 2,
                "liveWindowDuration": LIVE_WIN_LGTH,
                "scramblingType": "cpix",
            },
        )
        cl.Set_stream_adaptation_conf(
            "dash_time_scr",
            {
                "outputFormat": "dash",
                "subtitlesFormat": "ttmlpassthrough",
                "mpdTemplateType": "time",
                "chunkDuration": 2,
                "liveWindowDuration": LIVE_WIN_LGTH,
                "scramblingType": "cpix",
            },
        )
        cl.Set_stream_adaptation_conf(
            "hls_v3_ts_scr",
            {
                "outputFormat": "hls3",
                "subtitlesFormat": "dvbpassthrough",
                "mediaFormat": "ts",
                "chunkDuration": 2,
                "liveWindowDuration": LIVE_WIN_LGTH,
                "scramblingType": "cpix",
                "encryptionMethod": "aes",
            },
        )

        cl.Set_stream_adaptation_conf(
            "hls_v5_ts_scr",
            {
                "outputFormat": "hls5",
                "subtitlesFormat": "webvtt",
                "mediaFormat": "ts",
                "chunkDuration": 2,
                "liveWindowDuration": LIVE_WIN_LGTH,
                "scramblingType": "cpix",
                "encryptionMethod": "aes",
            },
        )
        cl.Set_stream_adaptation_conf(
            "hls_v7_fmp4_scr",
            {
                "outputFormat": "hls7",
                "subtitlesFormat": "webvtt",
                "mediaFormat": "fmp4",
                "chunkDuration": 2,
                "liveWindowDuration": LIVE_WIN_LGTH,
                "scramblingType": "cpix",
                "encryptionMethod": "sampleAes",
            },
        )
        cl.Set_stream_adaptation_conf(
            "hls_v7_ts_scr",
            {
                "outputFormat": "hls7",
                "subtitlesFormat": "webvtt",
                "mediaFormat": "ts",
                "chunkDuration": 2,
                "liveWindowDuration": LIVE_WIN_LGTH,
                "scramblingType": "cpix",
                "encryptionMethod": "aes",
            },
        )
        cl.Set_stream_adaptation_conf(
            "ss_20_scr",
            {
                "outputFormat": "smooth",
                "subtitlesFormat": "ttmlpassthrough",
                "liveWindowDuration": LIVE_WIN_LGTH,
                "scramblingType": "smoothFixed",
            },
        )
        cl.Set_stream_adaptation_conf(
            "ss_22_scr",
            {
                "outputFormat": "smooth22",
                "subtitlesFormat": "ttmlpassthrough",
                "liveWindowDuration": LIVE_WIN_LGTH,
                "scramblingType": "smoothFixed",
            },
        )

        # SAF
        cl.Set_stream_adaptation_family_conf(
            SAF,
            {
                "streamAdaptations": [
                    "dash_number_scr",
                    "dash_time_scr",
                    "hls_v3_ts_scr",
                    "hls_v5_ts_scr",
                    "hls_v7_ts_scr",
                    "hls_v7_fmp4_scr",
                    "ss_20_scr",
                    "ss_22_scr",
                    "cmaf_scr",
                ]
            },
        )
    else:
        # Free to air
        scrambling_Conf = []
        cl.Set_stream_adaptation_conf(
            "cmaf",
            {
                "outputFormat": "cmaf",
                "chunkDuration": 2,
                "liveWindowDuration": LIVE_WIN_LGTH,
                "subtitlesFormat": "imsc1",
            },
        )
        # cl.Set_stream_adaptation_conf(
        #     "dash_number",
        #     {
        #         "outputFormat": "dash",
        #         "mpdTemplateType": "number",
        #         "chunkDuration": 2,
        #         "liveWindowDuration": LIVE_WIN_LGTH,
        #         "subtitlesFormat": "ttmlpassthrough",
        #     },
        # )
        cl.Set_stream_adaptation_conf(
            "dash_time",
            {
                "outputFormat": "dash",
                "mpdTemplateType": "time",
                "chunkDuration": 2,
                "liveWindowDuration": LIVE_WIN_LGTH,
                "subtitlesFormat": "ttmlpassthrough",
            },
        )
        # cl.Set_stream_adaptation_conf(
        #     "hls_v3_ts",
        #     {
        #         "outputFormat": "hls3",
        #         "mediaFormat": "ts",
        #         "chunkDuration": 2,
        #         "liveWindowDuration": LIVE_WIN_LGTH,
        #     },
        # )
        # cl.Set_stream_adaptation_conf(
        #     "hls_v5_ts",
        #     {
        #         "outputFormat": "hls5",
        #         "mediaFormat": "ts",
        #         "chunkDuration": 2,
        #         "liveWindowDuration": LIVE_WIN_LGTH,
        #     },
        # )
        # cl.Set_stream_adaptation_conf(
        #     "hls_v7_fmp4",
        #     {
        #         "outputFormat": "hls7",
        #         "mediaFormat": "fmp4",
        #         "chunkDuration": 2,
        #         "liveWindowDuration": LIVE_WIN_LGTH,
        #     },
        # )
        # cl.Set_stream_adaptation_conf(
        #     "hls_v7_ts",
        #     {
        #         "outputFormat": "hls7",
        #         "mediaFormat": "ts",
        #         "chunkDuration": 2,
        #         "liveWindowDuration": LIVE_WIN_LGTH,
        #     },
        # )
        # cl.Set_stream_adaptation_conf(
        #     "ss_20",
        #     {
        #         "outputFormat": "smooth",
        #         "liveWindowDuration": LIVE_WIN_LGTH,
        #     },
        # )
        # cl.Set_stream_adaptation_conf(
        #     "ss_22",
        #     {
        #         "outputFormat": "smooth22",
        #         "liveWindowDuration": LIVE_WIN_LGTH,
        #     },
        # )

        # SAF
        cl.Set_stream_adaptation_family_conf(
            SAF,
            {
                "streamAdaptations": [
                    # "dash_number",
                    "dash_time",
                    # "hls_v3_ts",
                    # "hls_v5_ts",
                    # "hls_v7_ts",
                    # "hls_v7_fmp4",
                    # "ss_20",
                    # "ss_22",
                    "cmaf",
                ]
            },
        )


if os.getenv("CREATE_CHANNEL") == "1":
    common_options = {
        "archiveLifecycle": [
            {
                "action": "delete-unused-data",
                "durationOffset": DURATION_OFFSET,
                "disk": disk,
            },
            {
                "action": "delete-all-data",
                "durationOffset": DURATION_OFFSET,
                "disk": disk,
            },
        ],
        "streamAdaptationFamily": SAF,
        "scramblingConf": scrambling_Conf,
        "subtitles": {
            "dvbTxtConversion": True,
            "dvbSubConversion": True,
        },
    }

    print("Creating bench_channel_sd channels...")
    options = common_options.copy()
    options["streamAdaptationFamily"] = SAF
    options["sourceUris"] = sources_ip[1:6]
    for i in range(0, NB_CHANNEL):
        ch_name = f"{CHANNEL_NAME_PREFIXE}{i:03}"
        cl.Create_live_channel(ch_name, disk, _type, options)
        print("    ", ch_name)

if os.getenv("CREATE_NPVR_ASSETS") == "1":
    print("Creating nPVRs and archive as VOD job...")
    # ASOAP.waitChannels(list(options), TIMEOUT_CHECK_LIVE_ASSET)

    now = datetime.datetime.now(UTC()).replace(microsecond=0)
    date_range = {
        "begin": str(now.isoformat()),
        "end": str((now + datetime.timedelta(seconds=NPVR_DURATION)).isoformat()),
    }
    ch_name = f"bench_channel_{0:03}"
    npvr_conf = {
        "range": date_range,
        "useLiveChannelOutputSettings": False,
    }

    npvr_conf["streamAdaptationFamily"] = SAF
    npvr_conf["scramblingConf"] = scrambling_Conf
    npvr_conf["persistent"] = True
    # Create nPVR standard or infinite according to channel type
    cl.Create_npvr(NPVR_NAME, ch_name, npvr_conf)

    if os.getenv("CREATE_VOD_ASSETS") == "1":
        # Create a VOD asset from an nPVR
        job_conf = {
            "streamAdaptationFamily": npvr_conf["streamAdaptationFamily"],
            "scramblingConf": npvr_conf["scramblingConf"],
        }
        cl.Create_vod_job(
            "npvr://%s/%s" % (disk, NPVR_NAME),
            "vod://%s/%s" % (disk, VOD_NAME),
            job_conf,
        )


# subprocess.run(["ssh", f"amaint@{server_url_without_port}", "/etc/init.d/apache2", "restart"])
